-- create 
CREATE TABLESPACE OUTSOURCING
LOGGING
DATAFILE 'E:\oracle\oradata\orcl\OUTSOURCING_DATA01.DBF' 
SIZE 300M 
AUTOEXTEND ON 
NEXT 100M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL;
CREATE USER OutsourcingOfInformation IDENTIFIED BY agile932 DEFAULT TABLESPACE OUTSOURCING;
-- Grant/Revoke system privileges 
grant create any sequence to OUTSOURCINGOFINFORMATION;
grant create session to OUTSOURCINGOFINFORMATION;
grant create table to OUTSOURCINGOFINFORMATION;
grant drop any table to OUTSOURCINGOFINFORMATION;
grant insert any table to OUTSOURCINGOFINFORMATION;
grant update any table to OUTSOURCINGOFINFORMATION;