package com.zh.web.model.bean;

import java.util.Date;

import com.zh.core.model.IDataObject;

public class Express extends IDataObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXPRESS.ID
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXPRESS.EXPRESSNUMBER
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    private String expressnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXPRESS.COMPANY
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXPRESS.TELEPHONE
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXPRESS.DELIVERGOODSDATE
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    private Date delivergoodsdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXPRESS.ARRIVEDATE
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    private Date arrivedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXPRESS.TECHNOLOGICALPROCESSID
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    private Integer technologicalprocessid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXPRESS.ID
     *
     * @return the value of T_EXPRESS.ID
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXPRESS.ID
     *
     * @param id the value for T_EXPRESS.ID
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXPRESS.EXPRESSNUMBER
     *
     * @return the value of T_EXPRESS.EXPRESSNUMBER
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    public String getExpressnumber() {
        return expressnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXPRESS.EXPRESSNUMBER
     *
     * @param expressnumber the value for T_EXPRESS.EXPRESSNUMBER
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    public void setExpressnumber(String expressnumber) {
        this.expressnumber = expressnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXPRESS.COMPANY
     *
     * @return the value of T_EXPRESS.COMPANY
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXPRESS.COMPANY
     *
     * @param company the value for T_EXPRESS.COMPANY
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXPRESS.TELEPHONE
     *
     * @return the value of T_EXPRESS.TELEPHONE
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXPRESS.TELEPHONE
     *
     * @param telephone the value for T_EXPRESS.TELEPHONE
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXPRESS.DELIVERGOODSDATE
     *
     * @return the value of T_EXPRESS.DELIVERGOODSDATE
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    public Date getDelivergoodsdate() {
        return delivergoodsdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXPRESS.DELIVERGOODSDATE
     *
     * @param delivergoodsdate the value for T_EXPRESS.DELIVERGOODSDATE
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    public void setDelivergoodsdate(Date delivergoodsdate) {
        this.delivergoodsdate = delivergoodsdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXPRESS.ARRIVEDATE
     *
     * @return the value of T_EXPRESS.ARRIVEDATE
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    public Date getArrivedate() {
        return arrivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXPRESS.ARRIVEDATE
     *
     * @param arrivedate the value for T_EXPRESS.ARRIVEDATE
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    public void setArrivedate(Date arrivedate) {
        this.arrivedate = arrivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXPRESS.TECHNOLOGICALPROCESSID
     *
     * @return the value of T_EXPRESS.TECHNOLOGICALPROCESSID
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    public Integer getTechnologicalprocessid() {
        return technologicalprocessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXPRESS.TECHNOLOGICALPROCESSID
     *
     * @param technologicalprocessid the value for T_EXPRESS.TECHNOLOGICALPROCESSID
     *
     * @mbggenerated Wed Sep 10 09:11:20 CST 2014
     */
    public void setTechnologicalprocessid(Integer technologicalprocessid) {
        this.technologicalprocessid = technologicalprocessid;
    }
}