package com.zh.web.model.bean;

import com.zh.core.model.IDataObject;

/**
 * 加盟商信息
 * @author taozhaoping 26078
 * @author mail taozhaoping@gmail.com
 */
public class Franchisee extends IDataObject {
    
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_THE_FRANCHISEE.CREATEDATE
     *
     * @mbggenerated Sun Jan 04 10:22:32 CST 2015
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_THE_FRANCHISEE.UPDATEDATE
     *
     * @mbggenerated Sun Jan 04 10:22:32 CST 2015
     */
    private String updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_THE_FRANCHISEE.NAME
     *
     * @mbggenerated Sun Jan 04 10:22:32 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_THE_FRANCHISEE.DESCR
     *
     * @mbggenerated Sun Jan 04 10:22:32 CST 2015
     */
    private String descr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_THE_FRANCHISEE.ADDRESS
     *
     * @mbggenerated Sun Jan 04 10:22:32 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_THE_FRANCHISEE.STATUS
     *
     * @mbggenerated Sun Jan 04 10:22:32 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_THE_FRANCHISEE.CONTRACT_TYPE
     *
     * @mbggenerated Sun Jan 04 10:22:32 CST 2015
     */
    private String contractType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_THE_FRANCHISEE.CONTRACT_START_DATE
     *
     * @mbggenerated Sun Jan 04 10:22:32 CST 2015
     */
    private String contractStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_THE_FRANCHISEE.CONTRACT_END_DATE
     *
     * @mbggenerated Sun Jan 04 10:22:32 CST 2015
     */
    private String contractEndDate;
    
    private Integer createUserId;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCreatedate() {
		return createdate;
	}

	public void setCreatedate(String createdate) {
		this.createdate = createdate;
	}

	public String getUpdatedate() {
		return updatedate;
	}

	public void setUpdatedate(String updatedate) {
		this.updatedate = updatedate;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescr() {
		return descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getContractType() {
		return contractType;
	}

	public void setContractType(String contractType) {
		this.contractType = contractType;
	}

	public String getContractStartDate() {
		return contractStartDate;
	}

	public void setContractStartDate(String contractStartDate) {
		this.contractStartDate = contractStartDate;
	}

	public String getContractEndDate() {
		return contractEndDate;
	}

	public void setContractEndDate(String contractEndDate) {
		this.contractEndDate = contractEndDate;
	}

	public Integer getCreateUserId() {
		return createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

}