package com.zh.web.model.bean;

import java.util.Date;

public class Hotel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HOTEL.ID
     *
     * @mbggenerated Mon Oct 20 16:39:07 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HOTEL.NAME
     *
     * @mbggenerated Mon Oct 20 16:39:07 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HOTEL.ADDRESS
     *
     * @mbggenerated Mon Oct 20 16:39:07 CST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HOTEL.TELEPHONE
     *
     * @mbggenerated Mon Oct 20 16:39:07 CST 2014
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HOTEL.ROOMNUMBER
     *
     * @mbggenerated Mon Oct 20 16:39:07 CST 2014
     */
    private String roomNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HOTEL.ROOMTYPE
     *
     * @mbggenerated Mon Oct 20 16:39:07 CST 2014
     */
    private String roomType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HOTEL.SCHEDULEDATE
     *
     * @mbggenerated Mon Oct 20 16:39:07 CST 2014
     */
    private Date scheduleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HOTEL.SCHEDULEDAY
     *
     * @mbggenerated Mon Oct 20 16:39:07 CST 2014
     */
    private String scheduleDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HOTEL.CHECKINDATE
     *
     * @mbggenerated Mon Oct 20 16:39:07 CST 2014
     */
    private Date checkinDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HOTEL.CHECKINDAY
     *
     * @mbggenerated Mon Oct 20 16:39:07 CST 2014
     */
    private String checkinDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HOTEL.PRICE
     *
     * @mbggenerated Mon Oct 20 16:39:07 CST 2014
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HOTEL.CREATEDATE
     *
     * @mbggenerated Mon Oct 20 16:39:07 CST 2014
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HOTEL.UPDATEDATE
     *
     * @mbggenerated Mon Oct 20 16:39:07 CST 2014
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HOTEL.TECHNOLOGICALPROCESSID
     *
     * @mbggenerated Mon Oct 20 16:39:07 CST 2014
     */
    private Integer technologicalProcessId;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getRoomNumber() {
		return roomNumber;
	}

	public void setRoomNumber(String roomNumber) {
		this.roomNumber = roomNumber;
	}

	public String getRoomType() {
		return roomType;
	}

	public void setRoomType(String roomType) {
		this.roomType = roomType;
	}

	public Date getScheduleDate() {
		return scheduleDate;
	}

	public void setScheduleDate(Date scheduleDate) {
		this.scheduleDate = scheduleDate;
	}

	public String getScheduleDay() {
		return scheduleDay;
	}

	public void setScheduleDay(String scheduleDay) {
		this.scheduleDay = scheduleDay;
	}

	public Date getCheckinDate() {
		return checkinDate;
	}

	public void setCheckinDate(Date checkinDate) {
		this.checkinDate = checkinDate;
	}

	public String getCheckinDay() {
		return checkinDay;
	}

	public void setCheckinDay(String checkinDay) {
		this.checkinDay = checkinDay;
	}

	public String getPrice() {
		return price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getCreateDate() {
		return createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public String getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getTechnologicalProcessId() {
		return technologicalProcessId;
	}

	public void setTechnologicalProcessId(Integer technologicalProcessId) {
		this.technologicalProcessId = technologicalProcessId;
	}
}