package com.zh.web.model.bean;

import java.util.Date;

import com.zh.core.model.IDataObject;

/**
 * 员工正式信息表
 * @author taozhaoping 26078
 * @author mail taozhaoping@gmail.com
 */
public class Personnel extends IDataObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.ID
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.NAME
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.ENGLISHNAME
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String englishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.DESCRIPTION
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.DOMICILE
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String domicile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.PHONE
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.NATIONALITY
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.YEARBIRTH
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String yearBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.BIRTHDAY
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private Date birthDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.STATE
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.PASSPORTNO
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String passportno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.PASSPORTDATE
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private Date passportDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.VISATYPE
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String visaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.VISADATE
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private Date visaDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.CONTRACTTYPE
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String contractType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.CONTRACTDATE
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private Date contractDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.CREATEDATE
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.UPDATEDATE
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.MAIL
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.RES1
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String res1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.RES2
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String res2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.RES3
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String res3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.RES4
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String res4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.RES5
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String res5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONNEL.RES6
     *
     * @mbggenerated Fri Dec 26 11:36:55 CST 2014
     */
    private String res6;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEnglishName() {
		return englishName;
	}

	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDomicile() {
		return domicile;
	}

	public void setDomicile(String domicile) {
		this.domicile = domicile;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getNationality() {
		return nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public String getYearBirth() {
		return yearBirth;
	}

	public void setYearBirth(String yearBirth) {
		this.yearBirth = yearBirth;
	}

	public Date getBirthDay() {
		return birthDay;
	}

	public void setBirthDay(Date birthDay) {
		this.birthDay = birthDay;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getPassportno() {
		return passportno;
	}

	public void setPassportno(String passportno) {
		this.passportno = passportno;
	}

	public Date getPassportDate() {
		return passportDate;
	}

	public void setPassportDate(Date passportDate) {
		this.passportDate = passportDate;
	}

	public String getVisaType() {
		return visaType;
	}

	public void setVisaType(String visaType) {
		this.visaType = visaType;
	}

	public Date getVisaDate() {
		return visaDate;
	}

	public void setVisaDate(Date visaDate) {
		this.visaDate = visaDate;
	}

	public String getContractType() {
		return contractType;
	}

	public void setContractType(String contractType) {
		this.contractType = contractType;
	}

	public Date getContractDate() {
		return contractDate;
	}

	public void setContractDate(Date contractDate) {
		this.contractDate = contractDate;
	}

	public String getCreateDate() {
		return createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public String getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate;
	}

	public String getMail() {
		return mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getRes1() {
		return res1;
	}

	public void setRes1(String res1) {
		this.res1 = res1;
	}

	public String getRes2() {
		return res2;
	}

	public void setRes2(String res2) {
		this.res2 = res2;
	}

	public String getRes3() {
		return res3;
	}

	public void setRes3(String res3) {
		this.res3 = res3;
	}

	public String getRes4() {
		return res4;
	}

	public void setRes4(String res4) {
		this.res4 = res4;
	}

	public String getRes5() {
		return res5;
	}

	public void setRes5(String res5) {
		this.res5 = res5;
	}

	public String getRes6() {
		return res6;
	}

	public void setRes6(String res6) {
		this.res6 = res6;
	}

}